apiVersion: v1
kind: Service
metadata:
  name: frontend-patient-portal-ms
  namespace: argocd
  labels:
    app: frontend-patient-portal-ms
spec:
  ports:
    - port: 80
      protocol: TCP
      name: frontend-patient-portal-ms-ports
  selector:
    app: frontend-patient-portal-ms
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-patient-deployment
  namespace: argocd
  labels:
    app: frontend-patient-portal-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-patient-portal-ms
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend-patient-portal-ms
        tier: frontend
    spec: # Pod spec
      containers:
        - name: frontend-patient-container
          image: condorl/md-portal-ms:2.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"    # 500milliCPUs (1/2 CPU)
            limits:
              memory: "250Mi"
              cpu: "400m"
